# Generated by Django 5.2.4 on 2025-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN', 'Main Dish'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink')], default='MAIN', max_length=20),
        ),
    ]
